if: branch = master OR branch = devel
dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gdb

before_install:
  - pip install --user cpp-coveralls

jobs:
  include:
    - stage: debug_test
      name: Debug Test
      script:
        - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 . -DCMAKE_BUILD_TYPE=Debug
        - cmake --build .
        - gdb -q -x gdb_command ./run_tests
    - stage: Release Test
      name: Release Test
      script:
        - mkdir release_build
        - cd release_build
        - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCMAKE_BUILD_TYPE=Release ..
        - cmake --build .
        - ./run_tests

after_success:
  - echo "$TRAVIS_BUILD_STAGE_NAME" && test $TRAVIS_BUILD_STAGE_NAME = "Debug_test" && echo "Executing Coveralls" && coveralls --root . -E ".*external.*" -E ".*tests.cpp"  -E ".*examples.*"  -E ".*tests.cpp" -E ".*CMakeFiles.*"